version: '3.8'

services:
  app:
    build: .
    container_name: broomies-app
    ports:
      - "8080:8080"
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/broomies_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - broomies-network

  mysql_db:
    image: mysql:8.0
    container_name: broomies-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: broomies_db
    ports:
      - "3307:3306" # Mapped to 3307 to avoid conflict with local MySQL
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - broomies-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:


networks:
  broomies-network:
